import Script from "next/script";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark:bg-slate-950 dark:text-white">
      <body className={inter.className}>{children}</body>
      <Script
        defer
        data-domain="rsc-parser.vercel.app"
        src="/js/script.outbound-links.js"
      ></Script>
    </html>
  );
}
