import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { RscDevtoolsPanel } from '@rsc-parser/embedded';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="p-20">{children}</main>

        <RscDevtoolsPanel />
      </body>
    </html>
  );
}
